# Generated by Django 6.1 on 2026-08-12 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('agent_type', models.CharField(choices=[('content', 'Social Content Creator'), ('lead_finder', 'Lead Finder Specialist'), ('outreach', 'Outreach & Email Manager'), ('analyst', 'Analytics & Strategy Officer')], default='content', max_length=30)),
                ('avatar_icon', models.CharField(default='fa-robot', max_length=50)),
                ('avatar_color', models.CharField(default='#8b5cf6', max_length=50)),
                ('persona_description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active & Monitoring'), ('busy', 'Executing Workflow'), ('idle', 'Idle / Ready'), ('offline', 'Offline')], default='active', max_length=20)),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('success_rate', models.DecimalField(decimal_places=2, default=98.5, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('lead_gen', 'Lead Generation'), ('social_reach', 'Social Reach'), ('email_conversion', 'Email Conversions'), ('roi', 'ROI & Revenue')], default='lead_gen', max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=50)),
                ('change_percent', models.DecimalField(decimal_places=2, default=12.5, max_digits=5)),
                ('is_positive', models.BooleanField(default=True)),
                ('metric_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('objective', models.TextField()),
                ('target_audience', models.CharField(max_length=200)),
                ('budget', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='marketing.aiagent')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=150)),
                ('job_title', models.CharField(max_length=150)),
                ('industry', models.CharField(max_length=100)),
                ('lead_score', models.IntegerField(default=75)),
                ('score_tier', models.CharField(choices=[('hot', 'Hot Lead (80-100)'), ('warm', 'Warm Prospect (50-79)'), ('cold', 'Cold Contact (0-49)')], default='warm', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('replied', 'Replied'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('unresponsive', 'Unresponsive')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discovered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_leads', to='marketing.aiagent')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='marketing.marketingcampaign')),
            ],
        ),
        migrations.CreateModel(
            name='EmailOutreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('sequence_step', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('opened', 'Opened'), ('replied', 'Replied'), ('bounced', 'Bounced')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_emails', to='marketing.aiagent')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='marketing.lead')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_outreaches', to='marketing.marketingcampaign')),
            ],
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('twitter', 'Twitter / X'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], default='linkedin', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('hashtags', models.CharField(blank=True, max_length=300)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='marketing.aiagent')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='marketing.marketingcampaign')),
            ],
        ),
    ]
