# Generated by Django 6.1 on 2026-09-06 13:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_user_data_isolation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(help_text="Exact API identifier, for example 'openai/gpt-4o-mini'.", max_length=150)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('context_length', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_enabled', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('live', 'Fetched Live'), ('fallback', 'Curated Fallback'), ('manual', 'Added Manually')], default='fallback', max_length=10)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'LLM Model',
                'verbose_name_plural': 'LLM Models',
                'ordering': ['provider__provider_key', 'display_name', 'model_id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Workspace Owner'), ('manager', 'Marketing Manager'), ('analyst', 'Analyst'), ('viewer', 'Viewer')], default='owner', max_length=20)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('avatar_icon', models.CharField(default='fa-circle-user', max_length=50)),
                ('avatar_color', models.CharField(default='#4f46e5', max_length=20)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('bio', models.TextField(blank=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['user__username'],
            },
        ),
        migrations.AlterModelOptions(
            name='aiagent',
            options={'ordering': ['agent_type', 'name'], 'verbose_name': 'AI Employee', 'verbose_name_plural': 'AI Employees'},
        ),
        migrations.AlterModelOptions(
            name='analyticsmetric',
            options={'ordering': ['-metric_date'], 'verbose_name': 'Analytics Metric', 'verbose_name_plural': 'Analytics Metrics'},
        ),
        migrations.AlterModelOptions(
            name='emailoutreach',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Outreach Email', 'verbose_name_plural': 'Outreach Emails'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AlterModelOptions(
            name='marketingcampaign',
            options={'ordering': ['-created_at'], 'verbose_name': 'Marketing Campaign', 'verbose_name_plural': 'Marketing Campaigns'},
        ),
        migrations.AlterModelOptions(
            name='socialpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Social Post', 'verbose_name_plural': 'Social Posts'},
        ),
        migrations.AddField(
            model_name='aiagent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='max_tokens',
            field=models.PositiveIntegerField(default=800),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='system_prompt',
            field=models.TextField(blank=True, default='', help_text='Sent to the language model as the "system" role on every call.'),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=0.7, help_text='0.00 is deterministic, 2.00 is maximally creative.', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)]),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='emailoutreach',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aiagent',
            name='avatar_color',
            field=models.CharField(default='#4f46e5', max_length=50),
        ),
        migrations.AlterField(
            model_name='emailoutreach',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('opened', 'Opened'), ('replied', 'Replied'), ('bounced', 'Bounced')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('social_post', 'Social Media Post'), ('email', 'Outreach Email'), ('lead', 'Discovered Lead'), ('insight', 'Strategy Insight')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('payload_preview', models.TextField(blank=True, help_text='Human-readable snapshot of what the agent produced.')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('generation_source', models.CharField(choices=[('live', 'Live LLM Call'), ('fallback', 'Template Fallback'), ('manual', 'Created Manually')], default='fallback', max_length=10)),
                ('llm_model_used', models.CharField(blank=True, max_length=150)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='marketing.aiagent')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('email_outreach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='marketing.emailoutreach')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='marketing.lead')),
                ('social_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='marketing.socialpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval Request',
                'verbose_name_plural': 'Approval Queue',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Submitted for Review'), ('edited', 'Edited Before Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='marketing.approvalrequest')),
            ],
            options={
                'verbose_name': 'Approval Audit Entry',
                'verbose_name_plural': 'Approval Audit Trail',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='aiagent',
            name='llm_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='marketing.llmmodel'),
        ),
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_key', models.CharField(choices=[('openrouter', 'OpenRouter'), ('nvidia', 'NVIDIA NIM'), ('ollama', 'Ollama (Local)')], max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('base_url', models.CharField(blank=True, help_text='Leave blank to use the provider default.', max_length=200)),
                ('api_key', models.CharField(blank=True, help_text='Stored as plain text in this academic build. See llm_client.py.', max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('connection_status', models.CharField(choices=[('untested', 'Not Tested'), ('online', 'Online'), ('unauthorized', 'Invalid API Key'), ('error', 'Connection Error')], default='untested', max_length=20)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_message', models.CharField(blank=True, max_length=255)),
                ('last_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('models_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM Provider',
                'verbose_name_plural': 'LLM Providers',
                'ordering': ['provider_key'],
            },
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='marketing.llmprovider'),
        ),
        migrations.CreateModel(
            name='MCPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_key', models.CharField(choices=[('gmail', 'Gmail'), ('instagram', 'Instagram'), ('database', 'Database'), ('memory', 'Memory (Knowledge Graph)'), ('sequential_thinking', 'Sequential Thinking'), ('spotify', 'Spotify'), ('linkedin', 'LinkedIn')], max_length=30)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('communication', 'Communication'), ('social', 'Social Media'), ('data', 'Data & Storage'), ('reasoning', 'Reasoning'), ('media', 'Media')], default='data', max_length=20)),
                ('icon', models.CharField(default='fa-plug', max_length=50)),
                ('color', models.CharField(default='#4f46e5', max_length=20)),
                ('transport', models.CharField(choices=[('stdio', 'Standard I/O'), ('http', 'Streamable HTTP'), ('sse', 'Server-Sent Events')], default='stdio', max_length=10)),
                ('command', models.CharField(blank=True, help_text='Recorded for documentation only. This project never executes it.', max_length=200)),
                ('args', models.CharField(blank=True, max_length=300)),
                ('endpoint_url', models.CharField(blank=True, max_length=200)),
                ('auth_token', models.CharField(blank=True, max_length=255)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Extra settings, for example {"scopes": ["gmail.send"]}.')),
                ('is_enabled', models.BooleanField(default=True)),
                ('connection_status', models.CharField(choices=[('unknown', 'Never Connected'), ('connected', 'Connected'), ('degraded', 'Degraded'), ('failed', 'Handshake Failed'), ('disabled', 'Disabled')], default='unknown', max_length=20)),
                ('last_handshake_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_message', models.CharField(blank=True, max_length=255)),
                ('protocol_version', models.CharField(default='2025-06-18', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MCP Server',
                'verbose_name_plural': 'MCP Servers',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MCPTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(help_text="MCP tool identifier, for example 'send_email'.", max_length=80)),
                ('display_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_destructive', models.BooleanField(default=False, help_text='Tools that write to the outside world always require human approval.')),
                ('call_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='marketing.mcpserver')),
            ],
            options={
                'verbose_name': 'MCP Tool',
                'verbose_name_plural': 'MCP Tools',
                'ordering': ['server__name', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='MCPCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('result_summary', models.CharField(blank=True, max_length=300)),
                ('outcome', models.CharField(choices=[('ok', 'Success'), ('error', 'Error'), ('skipped', 'Skipped')], default='ok', max_length=10)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('called_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_calls', to='marketing.aiagent')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='marketing.mcptool')),
            ],
            options={
                'verbose_name': 'MCP Call Log',
                'verbose_name_plural': 'MCP Call Log',
                'ordering': ['-called_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentToolLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('attached_at', models.DateTimeField(auto_now_add=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_links', to='marketing.aiagent')),
                ('attached_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_attachments', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_links', to='marketing.mcptool')),
            ],
            options={
                'verbose_name': 'Agent Tool Attachment',
                'verbose_name_plural': 'Agent Tool Attachments',
                'ordering': ['tool__server__name', 'tool__display_name'],
            },
        ),
        migrations.AddField(
            model_name='aiagent',
            name='mcp_tools',
            field=models.ManyToManyField(blank=True, related_name='agents', through='marketing.AgentToolLink', to='marketing.mcptool'),
        ),
        migrations.AddConstraint(
            model_name='aiagent',
            constraint=models.UniqueConstraint(fields=('user', 'agent_type'), name='uniq_agent_type_per_user'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['user', 'status'], name='approval_user_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('email_outreach__isnull', True), ('lead__isnull', True), ('social_post__isnull', True)), models.Q(('email_outreach__isnull', True), ('lead__isnull', True), ('social_post__isnull', False)), models.Q(('email_outreach__isnull', False), ('lead__isnull', True), ('social_post__isnull', True)), models.Q(('email_outreach__isnull', True), ('lead__isnull', False), ('social_post__isnull', True)), _connector='OR'), name='approval_at_most_one_target'),
        ),
        migrations.AddConstraint(
            model_name='llmprovider',
            constraint=models.UniqueConstraint(fields=('user', 'provider_key'), name='uniq_provider_per_user'),
        ),
        migrations.AddIndex(
            model_name='llmmodel',
            index=models.Index(fields=['provider', 'is_enabled'], name='llmmodel_prov_enabled_idx'),
        ),
        migrations.AddConstraint(
            model_name='llmmodel',
            constraint=models.UniqueConstraint(fields=('provider', 'model_id'), name='uniq_model_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='mcpserver',
            constraint=models.UniqueConstraint(fields=('user', 'server_key'), name='uniq_mcp_server_per_user'),
        ),
        migrations.AddConstraint(
            model_name='mcptool',
            constraint=models.UniqueConstraint(fields=('server', 'tool_name'), name='uniq_tool_per_server'),
        ),
        migrations.AddConstraint(
            model_name='agenttoollink',
            constraint=models.UniqueConstraint(fields=('agent', 'tool'), name='uniq_tool_per_agent'),
        ),
    ]
