# Generated by Django 6.1 on 2026-09-06 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_merge_into_shared_workspace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalrequest',
            options={'ordering': ['-requested_at'], 'permissions': [('approve_approvalrequest', 'Can approve or reject queued work')], 'verbose_name': 'Approval Request', 'verbose_name_plural': 'Approval Queue'},
        ),
        migrations.AlterModelOptions(
            name='llmprovider',
            options={'ordering': ['provider_key'], 'permissions': [('test_llmprovider', 'Can test a provider connection and refresh its models')], 'verbose_name': 'LLM Provider', 'verbose_name_plural': 'LLM Providers'},
        ),
        migrations.AlterModelOptions(
            name='mcpserver',
            options={'ordering': ['category', 'name'], 'permissions': [('test_mcpserver', 'Can run the connection test on an MCP server')], 'verbose_name': 'MCP Server', 'verbose_name_plural': 'MCP Servers'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username'], 'permissions': [('assign_role', 'Can change which role a user holds')], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RemoveConstraint(
            model_name='aiagent',
            name='uniq_agent_type_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='llmprovider',
            name='uniq_provider_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='mcpserver',
            name='uniq_mcp_server_per_user',
        ),
        migrations.AddConstraint(
            model_name='aiagent',
            constraint=models.UniqueConstraint(fields=('agent_type',), name='uniq_agent_type_in_workspace'),
        ),
        migrations.AddConstraint(
            model_name='llmprovider',
            constraint=models.UniqueConstraint(fields=('provider_key',), name='uniq_provider_in_workspace'),
        ),
        migrations.AddConstraint(
            model_name='mcpserver',
            constraint=models.UniqueConstraint(fields=('server_key',), name='uniq_mcp_server_in_workspace'),
        ),
    ]
