# Generated by Django 6.1 on 2026-09-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_create_role_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailoutreach',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='When the message was handed to the mail server.', null=True),
        ),
        migrations.AddField(
            model_name='emailoutreach',
            name='delivery_error',
            field=models.TextField(blank=True, help_text='Why delivery failed, if it did. Empty on success.'),
        ),
    ]
