# Generated by Django 6.1 on 2026-09-06 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_email_delivery_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailoutreach',
            name='recipient_email',
            field=models.EmailField(blank=True, help_text='Used when the message is not addressed to a prospect on the pipeline.', max_length=254),
        ),
        migrations.AlterField(
            model_name='emailoutreach',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='marketing.lead'),
        ),
    ]
