# Generated by Django 6.1 on 2026-09-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_email_arbitrary_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Structured result attached to this reply, such as a mailbox listing or a ready-to-send draft. The template renders it as cards and buttons; the model never sees it.'),
        ),
    ]
