"""
Django settings for marketpulse project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from . import env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read BASE_DIR/.env into os.environ before any setting below is evaluated.
#
# A variable set with `$env:X = "y"` in PowerShell lives only as long as that
# one terminal window, so the next `manage.py runserver` would start with
# nothing and the site would quietly fall back to its offline behaviour --
# mail printed to the console instead of sent. The file is read on every
# start-up, however the server is launched.
#
# A real environment variable always wins over the file, and .env is listed in
# .gitignore so nothing secret is committed. See marketpulse/env.py.
env.load(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zy@af$ixk071jxi_^=8y9^z)*q390b=swf(kh%g9_6z%)sma7i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'marketing.apps.MarketingConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'marketpulse.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Supplies sidebar counters and the resolved theme to every template.
                'marketing.context_processors.workspace_chrome',
            ],
        },
    },
]

WSGI_APPLICATION = 'marketpulse.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Timestamps are STORED in UTC (USE_TZ = True below); this is only how they are
# DISPLAYED. It was previously 'UTC', which made the interface disagree with
# itself: Django rendered a reply at 17:00 while the browser stamped the
# message beside it 22:29, because one was UTC and the other was local.
# Change this to your own zone; the stored data does not move.
TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
#
# Approving an outreach email in the Approvals queue actually sends it. The
# credentials come from the environment, never from settings.py or the
# database, so a real mailbox password is not committed to version control.
#
# Put them in a .env file at the project root -- copy .env.example and fill it
# in -- so they survive closing the terminal:
#
#     EMAIL_HOST_USER=you@gmail.com
#     EMAIL_HOST_PASSWORD=your-app-password
#
# A real environment variable still overrides the file, which is how a server
# or CI would supply them instead:
#
#     PowerShell:  $env:EMAIL_HOST_USER = "you@gmail.com"
#     Bash:        export EMAIL_HOST_USER="you@gmail.com"
#
# For Gmail this must be an App Password, not the account password, and the
# account needs two-step verification enabled:
#     https://myaccount.google.com/apppasswords
# Google displays it in four groups of four; the spaces are presentation only
# and are stripped below.
#
# WITHOUT those variables the console backend is used instead, so approving an
# email prints it to the terminal rather than failing. That keeps the project
# demonstrable on a machine with no mail account at all.

EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '').strip()
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '').replace(' ', '')

EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = True
EMAIL_TIMEOUT = 20

EMAIL_BACKEND = (
    'django.core.mail.backends.smtp.EmailBackend'
    if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD
    else 'django.core.mail.backends.console.EmailBackend'
)

# What recipients see in the From header.
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or 'ai-workforce@localhost'
SERVER_EMAIL = DEFAULT_FROM_EMAIL


# Authentication redirects
# 'login' / 'dashboard' / 'landing' are URL *names* declared in marketing/urls.py.
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'landing'


# LLM provider client (marketing/llm_client.py)
#
# Two budgets, because the two kinds of call behave very differently.
# Listing models or testing a connection is cheap metadata and should fail
# fast. Generating a reply is not: a serverless endpoint that has scaled to
# zero can take 15-20 seconds to answer its first request, and a short timeout
# there would silently fall back to templates and make a working API key look
# broken.
LLM_HTTP_TIMEOUT = 8      # connection tests and model listings
LLM_CHAT_TIMEOUT = 60     # generating a reply

# API KEYS
# --------
# Keys are read from the environment when a provider has none stored, which
# keeps a real credential out of db.sqlite3 and out of version control:
#
#     PowerShell:  $env:NVIDIA_API_KEY = "nvapi-..."
#     Bash:        export NVIDIA_API_KEY="nvapi-..."
#
# Recognised names: OPENROUTER_API_KEY, NVIDIA_API_KEY. Ollama needs none.
# A key saved through the Configurations page still takes precedence.


# Messages
# Map Django's message levels onto the CSS tone names used by
# templates/partials/_messages.html.
from django.contrib.messages import constants as message_constants  # noqa: E402

MESSAGE_TAGS = {
    message_constants.DEBUG: 'info',
    message_constants.INFO: 'info',
    message_constants.SUCCESS: 'success',
    message_constants.WARNING: 'warning',
    message_constants.ERROR: 'danger',
}
